// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: src/proto/shoppingcart-service.proto

package shoppingcart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId int32   `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity  int32   `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceUnit float64 `protobuf:"fixed64,3,opt,name=priceUnit,proto3" json:"priceUnit,omitempty"`
}

func (x *AddProduct) Reset() {
	*x = AddProduct{}
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProduct) ProtoMessage() {}

func (x *AddProduct) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProduct.ProtoReflect.Descriptor instead.
func (*AddProduct) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcart_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddProduct) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProduct) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProduct) GetPriceUnit() float64 {
	if x != nil {
		return x.PriceUnit
	}
	return 0
}

type ShoppingCartTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuantityItems int32   `protobuf:"varint,1,opt,name=quantityItems,proto3" json:"quantityItems,omitempty"`
	PriceTotal    float64 `protobuf:"fixed64,2,opt,name=priceTotal,proto3" json:"priceTotal,omitempty"`
}

func (x *ShoppingCartTotal) Reset() {
	*x = ShoppingCartTotal{}
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingCartTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingCartTotal) ProtoMessage() {}

func (x *ShoppingCartTotal) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingCartTotal.ProtoReflect.Descriptor instead.
func (*ShoppingCartTotal) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcart_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingCartTotal) GetQuantityItems() int32 {
	if x != nil {
		return x.QuantityItems
	}
	return 0
}

func (x *ShoppingCartTotal) GetPriceTotal() float64 {
	if x != nil {
		return x.PriceTotal
	}
	return 0
}

var File_src_proto_shoppingcart_service_proto protoreflect.FileDescriptor

var file_src_proto_shoppingcart_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x63, 0x61, 0x72, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x63, 0x61, 0x72, 0x74, 0x22, 0x64, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x24, 0x0a, 0x0d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0x5f, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x28, 0x01, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x61, 0x72, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_shoppingcart_service_proto_rawDescOnce sync.Once
	file_src_proto_shoppingcart_service_proto_rawDescData = file_src_proto_shoppingcart_service_proto_rawDesc
)

func file_src_proto_shoppingcart_service_proto_rawDescGZIP() []byte {
	file_src_proto_shoppingcart_service_proto_rawDescOnce.Do(func() {
		file_src_proto_shoppingcart_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_shoppingcart_service_proto_rawDescData)
	})
	return file_src_proto_shoppingcart_service_proto_rawDescData
}

var file_src_proto_shoppingcart_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_shoppingcart_service_proto_goTypes = []any{
	(*AddProduct)(nil),        // 0: shoppingcart.AddProduct
	(*ShoppingCartTotal)(nil), // 1: shoppingcart.ShoppingCartTotal
}
var file_src_proto_shoppingcart_service_proto_depIdxs = []int32{
	0, // 0: shoppingcart.ShoppingCartService.AddItem:input_type -> shoppingcart.AddProduct
	1, // 1: shoppingcart.ShoppingCartService.AddItem:output_type -> shoppingcart.ShoppingCartTotal
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_shoppingcart_service_proto_init() }
func file_src_proto_shoppingcart_service_proto_init() {
	if File_src_proto_shoppingcart_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_shoppingcart_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_shoppingcart_service_proto_goTypes,
		DependencyIndexes: file_src_proto_shoppingcart_service_proto_depIdxs,
		MessageInfos:      file_src_proto_shoppingcart_service_proto_msgTypes,
	}.Build()
	File_src_proto_shoppingcart_service_proto = out.File
	file_src_proto_shoppingcart_service_proto_rawDesc = nil
	file_src_proto_shoppingcart_service_proto_goTypes = nil
	file_src_proto_shoppingcart_service_proto_depIdxs = nil
}
